[project]
name = "incept"
version = "0.1.115"
description = "A Python package for managing courses, projects, and directories with Notion integration."
readme = "README.md"
requires-python = ">=3.11,<4.0"
authors = [
  { name = "Suhail", email = "suhailece@gmail.com" },
]
dependencies = [
  "beautifulsoup4 >=4.13.4,<5.0.0",
  "browser-cookie3 >=0.20.1,<0.21.0",
  "click >=8.1.8,<9.0.0",
  "jinja2 >=3.1.5,<4.0.0",
  "notionmanager >=0.1.28,<0.2.0",
  "oauthmanager >=0.1.1,<0.2.0",
  "openpyxl >=3.1.5,<4.0.0",
  "packaging <24.3",
  "pandas >=2.2.3,<3.0.0",
  "pillow >=11.1.0,<12.0.0",
  "platformdirs >=3.0.0,<4.0.0",
  "prefect >=3.2.12,<4",
  "prefect-github >=0.3.0",
  "python-dotenv >=1.1.0,<2.0.0",
  "requests >=2.32.3,<3.0.0",
  "selenium >=4.31.0,<5.0.0",
  "tabulate >=0.9.0,<0.10.0",
  "webdriver-manager >=4.0.2,<5.0.0",
]
[project.scripts]
incept = "incept.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# Original [tool.poetry] has been migrated to PEP 621 by migrate2uv.sh
